//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative  grpctest.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: protos/grpc.proto

package gogrpctest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// частота запросов - N, по усолчанию 5
	Frequency uint64 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// информация, усредненная за последние M секунд, по усолчанию 15
	Period        uint64 `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestParams) Reset() {
	*x = RequestParams{}
	mi := &file_protos_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestParams) ProtoMessage() {}

func (x *RequestParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestParams.ProtoReflect.Descriptor instead.
func (*RequestParams) Descriptor() ([]byte, []int) {
	return file_protos_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *RequestParams) GetFrequency() uint64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *RequestParams) GetPeriod() uint64 {
	if x != nil {
		return x.Period
	}
	return 0
}

type ResponseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// float metric = 1;
	Metrics       string `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseData) Reset() {
	*x = ResponseData{}
	mi := &file_protos_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseData) ProtoMessage() {}

func (x *ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseData.ProtoReflect.Descriptor instead.
func (*ResponseData) Descriptor() ([]byte, []int) {
	return file_protos_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseData) GetMetrics() string {
	if x != nil {
		return x.Metrics
	}
	return ""
}

var File_protos_grpc_proto protoreflect.FileDescriptor

const file_protos_grpc_proto_rawDesc = "" +
	"\n" +
	"\x11protos/grpc.proto\x12\n" +
	"gogrpctest\"E\n" +
	"\rRequestParams\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\x04R\tfrequency\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x04R\x06period\"(\n" +
	"\fResponseData\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\tR\ametrics2`\n" +
	"\x10StreamingService\x12L\n" +
	"\x11GetDataFromStream\x12\x19.gogrpctest.RequestParams\x1a\x18.gogrpctest.ResponseData\"\x000\x01B\x0eZ\f./gogrpctestb\x06proto3"

var (
	file_protos_grpc_proto_rawDescOnce sync.Once
	file_protos_grpc_proto_rawDescData []byte
)

func file_protos_grpc_proto_rawDescGZIP() []byte {
	file_protos_grpc_proto_rawDescOnce.Do(func() {
		file_protos_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_grpc_proto_rawDesc), len(file_protos_grpc_proto_rawDesc)))
	})
	return file_protos_grpc_proto_rawDescData
}

var file_protos_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_grpc_proto_goTypes = []any{
	(*RequestParams)(nil), // 0: gogrpctest.RequestParams
	(*ResponseData)(nil),  // 1: gogrpctest.ResponseData
}
var file_protos_grpc_proto_depIdxs = []int32{
	0, // 0: gogrpctest.StreamingService.GetDataFromStream:input_type -> gogrpctest.RequestParams
	1, // 1: gogrpctest.StreamingService.GetDataFromStream:output_type -> gogrpctest.ResponseData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_grpc_proto_init() }
func file_protos_grpc_proto_init() {
	if File_protos_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_grpc_proto_rawDesc), len(file_protos_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_grpc_proto_goTypes,
		DependencyIndexes: file_protos_grpc_proto_depIdxs,
		MessageInfos:      file_protos_grpc_proto_msgTypes,
	}.Build()
	File_protos_grpc_proto = out.File
	file_protos_grpc_proto_goTypes = nil
	file_protos_grpc_proto_depIdxs = nil
}
