LinuxMetrics:
 -
    name: "Load avg. (%)"
    cmd: "cat"
    cmdParams: "/proc/loadavg"
    parseParams: "{print $1}"
    isActive: true
 -
    name: "Cpu load (%)"
    cmd: "top"
    cmdParams: "-b"
    parseParams: '$1=="%Cpu(s):"{print $2}'
    isActive: false

WindowsMetrics:
 -
    name: "Cpu load (%)"
    cmd: 'Get-Counter -Counter "\Процессор(_Total)\% загруженности процессора" | Foreach-Object {$_.CounterSamples[0].CookedValue}'
    isActive: true
 -
    name: "Hdd load (%)"
    cmd: 'Get-Counter -Counter "\Физический диск(_Total)\% активности диска" | Foreach-Object {$_.CounterSamples[0].CookedValue}'
    isActive: true